spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vacation_calculator_db
    username: postgres
    password: postgres
    hikari:
      schema: vacation_calculator_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS vacation_calculator_schema